# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import carla_pb2 as carla__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in carla_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarlaAdapterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteOneTimeStep = channel.unary_unary(
                '/carla.CarlaAdapter/ExecuteOneTimeStep',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=carla__pb2.Boolean.FromString,
                _registered_method=True)
        self.Finish = channel.unary_unary(
                '/carla.CarlaAdapter/Finish',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetManagedActorsIds = channel.unary_unary(
                '/carla.CarlaAdapter/GetManagedActorsIds',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=carla__pb2.ActorIds.FromString,
                _registered_method=True)
        self.GetManagedCAVsIds = channel.unary_unary(
                '/carla.CarlaAdapter/GetManagedCAVsIds',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=carla__pb2.ActorIds.FromString,
                _registered_method=True)
        self.GetManagedActorById = channel.unary_unary(
                '/carla.CarlaAdapter/GetManagedActorById',
                request_serializer=carla__pb2.Number.SerializeToString,
                response_deserializer=carla__pb2.Vehicle.FromString,
                _registered_method=True)
        self.InsertVehicle = channel.unary_unary(
                '/carla.CarlaAdapter/InsertVehicle',
                request_serializer=carla__pb2.Vehicle.SerializeToString,
                response_deserializer=carla__pb2.Number.FromString,
                _registered_method=True)
        self.GetRandomSpawnPoint = channel.unary_unary(
                '/carla.CarlaAdapter/GetRandomSpawnPoint',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=carla__pb2.Transform.FromString,
                _registered_method=True)
        self.GetActorLDM = channel.unary_unary(
                '/carla.CarlaAdapter/GetActorLDM',
                request_serializer=carla__pb2.Number.SerializeToString,
                response_deserializer=carla__pb2.Objects.FromString,
                _registered_method=True)
        self.InsertObject = channel.unary_unary(
                '/carla.CarlaAdapter/InsertObject',
                request_serializer=carla__pb2.ObjectIn.SerializeToString,
                response_deserializer=carla__pb2.Number.FromString,
                _registered_method=True)
        self.InsertObjects = channel.unary_unary(
                '/carla.CarlaAdapter/InsertObjects',
                request_serializer=carla__pb2.ObjectsIn.SerializeToString,
                response_deserializer=carla__pb2.DoubleValue.FromString,
                _registered_method=True)
        self.InsertCV = channel.unary_unary(
                '/carla.CarlaAdapter/InsertCV',
                request_serializer=carla__pb2.ObjectIn.SerializeToString,
                response_deserializer=carla__pb2.DoubleValue.FromString,
                _registered_method=True)
        self.GetCartesian = channel.unary_unary(
                '/carla.CarlaAdapter/GetCartesian',
                request_serializer=carla__pb2.Vector.SerializeToString,
                response_deserializer=carla__pb2.Vector.FromString,
                _registered_method=True)
        self.GetGeo = channel.unary_unary(
                '/carla.CarlaAdapter/GetGeo',
                request_serializer=carla__pb2.Vector.SerializeToString,
                response_deserializer=carla__pb2.Vector.FromString,
                _registered_method=True)
        self.hasLDM = channel.unary_unary(
                '/carla.CarlaAdapter/hasLDM',
                request_serializer=carla__pb2.Number.SerializeToString,
                response_deserializer=carla__pb2.Boolean.FromString,
                _registered_method=True)
        self.SetControl = channel.unary_unary(
                '/carla.CarlaAdapter/SetControl',
                request_serializer=carla__pb2.Control.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCarlaWaypoint = channel.unary_unary(
                '/carla.CarlaAdapter/GetCarlaWaypoint',
                request_serializer=carla__pb2.Vector.SerializeToString,
                response_deserializer=carla__pb2.Waypoint.FromString,
                _registered_method=True)
        self.GetNextCarlaWaypoint = channel.unary_unary(
                '/carla.CarlaAdapter/GetNextCarlaWaypoint',
                request_serializer=carla__pb2.Vector.SerializeToString,
                response_deserializer=carla__pb2.Waypoint.FromString,
                _registered_method=True)
        self.GetGTaccuracy = channel.unary_unary(
                '/carla.CarlaAdapter/GetGTaccuracy',
                request_serializer=carla__pb2.ObjectMinimal.SerializeToString,
                response_deserializer=carla__pb2.DoubleValue.FromString,
                _registered_method=True)


class CarlaAdapterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteOneTimeStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManagedActorsIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManagedCAVsIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManagedActorById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertVehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRandomSpawnPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorLDM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertCV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCartesian(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGeo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def hasLDM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarlaWaypoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextCarlaWaypoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGTaccuracy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarlaAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteOneTimeStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOneTimeStep,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=carla__pb2.Boolean.SerializeToString,
            ),
            'Finish': grpc.unary_unary_rpc_method_handler(
                    servicer.Finish,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetManagedActorsIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManagedActorsIds,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=carla__pb2.ActorIds.SerializeToString,
            ),
            'GetManagedCAVsIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManagedCAVsIds,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=carla__pb2.ActorIds.SerializeToString,
            ),
            'GetManagedActorById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManagedActorById,
                    request_deserializer=carla__pb2.Number.FromString,
                    response_serializer=carla__pb2.Vehicle.SerializeToString,
            ),
            'InsertVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertVehicle,
                    request_deserializer=carla__pb2.Vehicle.FromString,
                    response_serializer=carla__pb2.Number.SerializeToString,
            ),
            'GetRandomSpawnPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandomSpawnPoint,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=carla__pb2.Transform.SerializeToString,
            ),
            'GetActorLDM': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorLDM,
                    request_deserializer=carla__pb2.Number.FromString,
                    response_serializer=carla__pb2.Objects.SerializeToString,
            ),
            'InsertObject': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertObject,
                    request_deserializer=carla__pb2.ObjectIn.FromString,
                    response_serializer=carla__pb2.Number.SerializeToString,
            ),
            'InsertObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertObjects,
                    request_deserializer=carla__pb2.ObjectsIn.FromString,
                    response_serializer=carla__pb2.DoubleValue.SerializeToString,
            ),
            'InsertCV': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertCV,
                    request_deserializer=carla__pb2.ObjectIn.FromString,
                    response_serializer=carla__pb2.DoubleValue.SerializeToString,
            ),
            'GetCartesian': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCartesian,
                    request_deserializer=carla__pb2.Vector.FromString,
                    response_serializer=carla__pb2.Vector.SerializeToString,
            ),
            'GetGeo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGeo,
                    request_deserializer=carla__pb2.Vector.FromString,
                    response_serializer=carla__pb2.Vector.SerializeToString,
            ),
            'hasLDM': grpc.unary_unary_rpc_method_handler(
                    servicer.hasLDM,
                    request_deserializer=carla__pb2.Number.FromString,
                    response_serializer=carla__pb2.Boolean.SerializeToString,
            ),
            'SetControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControl,
                    request_deserializer=carla__pb2.Control.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCarlaWaypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarlaWaypoint,
                    request_deserializer=carla__pb2.Vector.FromString,
                    response_serializer=carla__pb2.Waypoint.SerializeToString,
            ),
            'GetNextCarlaWaypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextCarlaWaypoint,
                    request_deserializer=carla__pb2.Vector.FromString,
                    response_serializer=carla__pb2.Waypoint.SerializeToString,
            ),
            'GetGTaccuracy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGTaccuracy,
                    request_deserializer=carla__pb2.ObjectMinimal.FromString,
                    response_serializer=carla__pb2.DoubleValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carla.CarlaAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('carla.CarlaAdapter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarlaAdapter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteOneTimeStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/ExecuteOneTimeStep',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            carla__pb2.Boolean.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/Finish',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManagedActorsIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetManagedActorsIds',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            carla__pb2.ActorIds.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManagedCAVsIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetManagedCAVsIds',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            carla__pb2.ActorIds.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManagedActorById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetManagedActorById',
            carla__pb2.Number.SerializeToString,
            carla__pb2.Vehicle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/InsertVehicle',
            carla__pb2.Vehicle.SerializeToString,
            carla__pb2.Number.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRandomSpawnPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetRandomSpawnPoint',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            carla__pb2.Transform.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActorLDM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetActorLDM',
            carla__pb2.Number.SerializeToString,
            carla__pb2.Objects.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/InsertObject',
            carla__pb2.ObjectIn.SerializeToString,
            carla__pb2.Number.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/InsertObjects',
            carla__pb2.ObjectsIn.SerializeToString,
            carla__pb2.DoubleValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertCV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/InsertCV',
            carla__pb2.ObjectIn.SerializeToString,
            carla__pb2.DoubleValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCartesian(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetCartesian',
            carla__pb2.Vector.SerializeToString,
            carla__pb2.Vector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGeo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetGeo',
            carla__pb2.Vector.SerializeToString,
            carla__pb2.Vector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def hasLDM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/hasLDM',
            carla__pb2.Number.SerializeToString,
            carla__pb2.Boolean.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/SetControl',
            carla__pb2.Control.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarlaWaypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetCarlaWaypoint',
            carla__pb2.Vector.SerializeToString,
            carla__pb2.Waypoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextCarlaWaypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetNextCarlaWaypoint',
            carla__pb2.Vector.SerializeToString,
            carla__pb2.Waypoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGTaccuracy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla.CarlaAdapter/GetGTaccuracy',
            carla__pb2.ObjectMinimal.SerializeToString,
            carla__pb2.DoubleValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
